[package]
name = "distribution_select"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "3"
rand = "0.8"

[dev-dependencies]
hash_histogram = "0.6"